services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
      - ./logs:/home/node/app/logs
